import { useEffect, useState } from "react";

import Head from "next/head";
import { Contacts } from "components";
import { ContactsProvider } from "hooks";

import styles from "./Index.module.scss";

export default function Home() {
  return (
    <>
      <Head>
        <title>Contactify</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ContactsProvider>
        <div className={styles.mainLayout}>
          <Contacts />
        </div>
      </ContactsProvider>
    </>
  );
}
